//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleWPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int ID_Call { get; set; }
        public string Adress { get; set; }
        public string Problem { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public bool IsDone { get; set; }
    
        public virtual Masters Masters { get; set; }
    }
}
